"""Задание 2.
В файле создать примеры использования как можно большего количества операторов."""
x = int(input("first number\t"))
y = int(input('second number\t'))
if x > 0 and y > 0:
    print(f'{x + y}')
    print(f'{x - y}')
    print(f'{x * y}')
    print(f'{x / y}')
    print(f'{x % y}')
    print(f'{x ** y}')
    print(f'{x // y}')
    print(f'{x == y}')
    print(f'{x != y}')
    print(f'{x > y}')
    print(f'{x < y}')
    print(f'{x >= y}')
    print(f'{x <= y}')
    print(f'{x & y}')
    print(f'{x | y}')
    print(f'{x ^ y}')
    print(f'{x << y}')
    print(f'{x >> y}')
